import { Inter } from "next/font/google";
import { ThemeProvider } from "@providers/ThemeProvider";
import Navbar from "@components/Navbar";

import "@styles/globals.css";
import Cursor from "@components/ui/cursor";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <Cursor />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
